let numberX = 10;
let numberY = 20;
let result = numberX + numberY;
console.log(result);
result += 10;
console.log(result);
result -= 10;
console.log(result);
result *= 10;
console.log(result);
result /= 10;
console.log(result);
result %= 10;
console.log(result);
result **= 10;
console.log(result);
result += 10 + numberY;
console.log(result);
result *= numberX - numberY;
console.log(result); 